//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportSarfasl.dataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_ReportView
    {
        public Nullable<int> ZID { get; set; }
        public int ZSarfaslID { get; set; }
        public string ZName { get; set; }
        public string Zhas_dar { get; set; }
        public decimal Expr5 { get; set; }
        public Nullable<bool> ZActive { get; set; }
        public int SID { get; set; }
        public string SName { get; set; }
        public string Shas_dar { get; set; }
        public string Swho_def { get; set; }
        public string start_date { get; set; }
        public Nullable<bool> SActive { get; set; }
        public int SGroupSarfaslID { get; set; }
    }
}
